FROM mysql:8.0
COPY dump.sql /tmp/
#RUN /bin/bash -c "/usr/bin/mysqld_safe --skip-grant-tables &" && \
#  sleep 5 && \
#  mysql -u root -e "CREATE DATABASE vakomsTestBlog"
#RUN mysql start
#RUN  mysql -u root -e "CREATE DATABASE vakomsTestBlog"
#  mysql -u root vakomsTestBlog < /tmp/dump.sql
#RUN mysql -u root -p vakomsTestBlog < /code/dumb.sql